# Pandas Session 1 Assignment: IBM HR Analytics

## Employee Attrition Analysis

**Dataset:** IBM HR Analytics Employee Attrition and Performance

**Source:** Kaggle - https://www.kaggle.com/datasets/pavansubhasht/ibm-hr-analytics-attrition-dataset

---

### Learning Objectives

This assignment tests your understanding of Session 1 concepts:

- Loading and exploring data with pandas
- Using describe(), info(), shape, dtypes
- Selecting data with loc and iloc
- Boolean filtering and conditional selection
- Using value_counts() for categorical analysis
- Applying functions with apply() and map()
- Basic data manipulation and sorting

---

### Dataset Description

This is a fictional dataset created by IBM data scientists to understand factors that lead to employee attrition.

**Key Columns:**

- Age, Gender, MaritalStatus - Demographics
- Department, JobRole, JobLevel - Job information
- MonthlyIncome, HourlyRate, DailyRate - Compensation
- YearsAtCompany, YearsInCurrentRole, TotalWorkingYears - Experience
- Attrition - Target variable (Yes/No - did employee leave?)
- JobSatisfaction, EnvironmentSatisfaction - Satisfaction scores (1-4)
- WorkLifeBalance, PerformanceRating - Performance metrics

---

### Instructions

1. Download the dataset from Kaggle or use the direct URL provided
2. Complete each task in the cells provided
3. Write clean, commented code
4. Answer the analysis questions in markdown cells

**Total Points: 100 (+ 10 bonus)**

---
## Part 1: Data Loading and Initial Exploration (15 points)
---

In [86]:
import pandas as pd
import numpy as np

# Load the dataset
# Option 1: From Kaggle (download first)
# df = pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.csv')

# Option 2: From GitHub mirror
url = 'https://raw.githubusercontent.com/IBM/employee-attrition-aif360/master/data/emp_attrition.csv'
df = pd.read_csv(url)

print('Dataset loaded successfully!')
print(f'Shape: {df.shape}')

Dataset loaded successfully!
Shape: (1470, 35)

### Task 1.1: Basic Exploration (5 points)

1. Display the first 10 rows of the dataset
2. Display the last 5 rows
3. Show the shape of the dataset (rows, columns)
4. List all column names

In [87]:
### 1. Display the first 10 rows of the dataset
df.head(10)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
5,32,No,Travel_Frequently,1005,Research & Development,2,2,Life Sciences,1,8,...,3,80,0,8,2,2,7,7,3,6
6,59,No,Travel_Rarely,1324,Research & Development,3,3,Medical,1,10,...,1,80,3,12,3,2,1,0,0,0
7,30,No,Travel_Rarely,1358,Research & Development,24,1,Life Sciences,1,11,...,2,80,1,1,2,3,1,0,0,0
8,38,No,Travel_Frequently,216,Research & Development,23,3,Life Sciences,1,12,...,2,80,0,10,2,3,9,7,1,8
9,36,No,Travel_Rarely,1299,Research & Development,27,3,Medical,1,13,...,2,80,2,17,3,2,7,7,7,7

In [88]:
### 2. Display the last 5 rows
df.tail()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [89]:
### 3. Show the shape of the dataset (rows, columns)
df.shape

(1470, 35)

In [90]:
### 4.List all column names
df.columns.tolist()

['Age',
 'Attrition',
 'BusinessTravel',
 'DailyRate',
 'Department',
 'DistanceFromHome',
 'Education',
 'EducationField',
 'EmployeeCount',
 'EmployeeNumber',
 'EnvironmentSatisfaction',
 'Gender',
 'HourlyRate',
 'JobInvolvement',
 'JobLevel',
 'JobRole',
 'JobSatisfaction',
 'MaritalStatus',
 'MonthlyIncome',
 'MonthlyRate',
 'NumCompaniesWorked',
 'Over18',
 'OverTime',
 'PercentSalaryHike',
 'PerformanceRating',
 'RelationshipSatisfaction',
 'StandardHours',
 'StockOptionLevel',
 'TotalWorkingYears',
 'TrainingTimesLastYear',
 'WorkLifeBalance',
 'YearsAtCompany',
 'YearsInCurrentRole',
 'YearsSinceLastPromotion',
 'YearsWithCurrManager']

### Task 1.2: Data Types and Info (5 points)

1. Use info() to display column data types and non-null counts
2. Use dtypes to show just the data types
3. How many numeric columns are there? How many object columns?

In [91]:
### 1.Use info() to display column data types and non-null counts
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [92]:
### 2.Use dtypes to show just the data types
df.dtypes

Age                          int64
Attrition                   object
BusinessTravel              object
DailyRate                    int64
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EmployeeCount                int64
EmployeeNumber               int64
EnvironmentSatisfaction      int64
Gender                      object
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
MonthlyRate                  int64
NumCompaniesWorked           int64
Over18                      object
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StandardHours                int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

In [93]:
###3.How many numeric columns are there?
len(df.select_dtypes(include=['number']).columns)

26

In [94]:
# How many object columns?
len(df.select_dtypes(include=['object']).columns)

9

### Task 1.3: Statistical Summary (5 points)

1. Use describe() to get summary statistics for numeric columns
2. Use describe(include='object') for categorical columns
3. What is the average MonthlyIncome? What is the median Age?

In [95]:
###1.Use describe() to get summary statistics for numeric columns
df.describe()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,802.485714,9.192517,2.912925,1.0,1024.865306,2.721769,65.891156,2.729932,2.063946,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,403.509100,8.106864,1.024165,0.0,602.024335,1.093082,20.329428,0.711561,1.106940,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,102.000000,1.000000,1.000000,1.0,1.000000,1.000000,30.000000,1.000000,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,465.000000,2.000000,2.000000,1.0,491.250000,2.000000,48.000000,2.000000,1.000000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,802.000000,7.000000,3.000000,1.0,1020.500000,3.000000,66.000000,3.000000,2.000000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,1157.000000,14.000000,4.000000,1.0,1555.750000,4.000000,83.750000,3.000000,3.000000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1499.000000,29.000000,5.000000,1.0,2068.000000,4.000000,100.000000,4.000000,5.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

In [96]:
###2.Use describe(include='object') for categorical columns
df.describe(include='object')

,Attrition,BusinessTravel,Department,EducationField,Gender,JobRole,MaritalStatus,Over18,OverTime
count,1470,1470,1470,1470,1470,1470,1470,1470,1470
unique,2,3,3,6,2,9,3,1,2
top,No,Travel_Rarely,Research & Development,Life Sciences,Male,Sales Executive,Married,Y,No
freq,1233,1043,961,606,882,326,673,1470,1054

In [97]:
###3.What is the average MonthlyIncome? What is the median Age?
print(df['MonthlyIncome'].mean())
print(df['Age'].median())

6502.931292517007
36.0

---
## Part 2: Indexing and Selection (15 points)
---

### Task 2.1: Selection with loc - Label-based (5 points)

Use loc to:

1. Select the first 5 rows and columns: 'Age', 'Department', 'MonthlyIncome', 'Attrition'
2. Select rows 10 to 20 (inclusive) and columns from 'Age' to 'Department'
3. Select all rows where index is less than 10, showing only 'EmployeeNumber' and 'JobRole'

In [98]:
###1.Select the first 5 rows and columns: 'Age', 'Department', 'MonthlyIncome', 'Attrition'
df.loc[:4, ['Age', 'Department', 'MonthlyIncome', 'Attrition']]

   Age              Department  MonthlyIncome Attrition
0   41                   Sales           5993       Yes
1   49  Research & Development           5130        No
2   37  Research & Development           2090       Yes
3   33  Research & Development           2909        No
4   27  Research & Development           3468        No

In [99]:
###2.Select rows 10 to 20 (inclusive) and columns from 'Age' to 'Department'
df.loc[10:21, 'Age':'Department']

    Age Attrition BusinessTravel  DailyRate              Department
10   35        No  Travel_Rarely        809  Research & Development
11   29        No  Travel_Rarely        153  Research & Development
12   31        No  Travel_Rarely        670  Research & Development
13   34        No  Travel_Rarely       1346  Research & Development
14   28       Yes  Travel_Rarely        103  Research & Development
15   29        No  Travel_Rarely       1389  Research & Development
16   32        No  Travel_Rarely        334  Research & Development
17   22        No     Non-Travel       1123  Research & Development
18   53        No  Travel_Rarely       1219                   Sales
19   38        No  Travel_Rarely        371  Research & Development
20   24        No     Non-Travel        673  Research & Development
21   36       Yes  Travel_Rarely       1218                   Sales

In [100]:
###3.Select all rows where index is less than 10, showing only 'EmployeeNumber' and 'JobRole'
df.loc[df.index < 10, ['EmployeeNumber' , 'JobRole']]

   EmployeeNumber                    JobRole
0               1            Sales Executive
1               2         Research Scientist
2               4      Laboratory Technician
3               5         Research Scientist
4               7      Laboratory Technician
5               8      Laboratory Technician
6              10      Laboratory Technician
7              11      Laboratory Technician
8              12     Manufacturing Director
9              13  Healthcare Representative

### Task 2.2: Selection with iloc - Integer-based (5 points)

Use iloc to:

1. Select the first 10 rows and first 5 columns
2. Select every 100th row (row 0, 100, 200, etc.) and the last 3 columns
3. Select rows 50-60 and columns at positions 0, 2, 4, 6

In [101]:
###1.Select the first 10 rows and first 5 columns
df.iloc[:10, :5]

   Age Attrition     BusinessTravel  DailyRate              Department
0   41       Yes      Travel_Rarely       1102                   Sales
1   49        No  Travel_Frequently        279  Research & Development
2   37       Yes      Travel_Rarely       1373  Research & Development
3   33        No  Travel_Frequently       1392  Research & Development
4   27        No      Travel_Rarely        591  Research & Development
5   32        No  Travel_Frequently       1005  Research & Development
6   59        No      Travel_Rarely       1324  Research & Development
7   30        No      Travel_Rarely       1358  Research & Development
8   38        No  Travel_Frequently        216  Research & Development
9   36        No      Travel_Rarely       1299  Research & Development

In [102]:
###2.Select every 100th row (row 0, 100, 200, etc.) and the last 3 columns
df.iloc[::100, -4:-1]

      YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion
0                  6                   4                        0
100                3                   2                        0
200                2                   2                        2
300               22                  10                        0
400               21                   8                        1
500                6                   4                        0
600               14                  13                        6
700                1                   0                        0
800                1                   0                        0
900               11                  10                        0
1000               5                   4                        0
1100               5                   3                        4
1200               2                   2                        2
1300              10                   8                        4
1400               6                   2                        1

In [103]:
###3.Select rows 50-60 and columns at positions 0, 2, 4, 6
df.iloc[50:61, :7:2]

    Age     BusinessTravel              Department  Education
50   48      Travel_Rarely  Research & Development          2
51   28      Travel_Rarely  Research & Development          4
52   44      Travel_Rarely                   Sales          5
53   35         Non-Travel  Research & Development          2
54   26      Travel_Rarely                   Sales          3
55   33  Travel_Frequently  Research & Development          2
56   35  Travel_Frequently                   Sales          5
57   35      Travel_Rarely  Research & Development          4
58   31      Travel_Rarely  Research & Development          4
59   37      Travel_Rarely  Research & Development          4
60   32      Travel_Rarely  Research & Development          3

### Task 2.3: loc vs iloc Understanding (5 points)

Demonstrate and explain:

1. Show that loc[0:5] returns 6 rows (inclusive end)
2. Show that iloc[0:5] returns 5 rows (exclusive end)
3. What happens if you use iloc with column names? Try it.

In [104]:
###1.Show that loc[0:5] returns 6 rows (inclusive end)
df.loc[0:5]
# while using loc, the end of index is included

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
5,32,No,Travel_Frequently,1005,Research & Development,2,2,Life Sciences,1,8,...,3,80,0,8,2,2,7,7,3,6

In [105]:
###2.Show that iloc[0:5] returns 5 rows (exclusive end)
df.iloc[0:5]
# iloc function excludes the end of the index.

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [106]:
###3.What happens if you use iloc with column names? Try it.
df.iloc['Age', 'Department']
# gives an error as iloc is index_based NOT label_based.

---
## Part 3: Boolean Filtering (20 points)
---

### Task 3.1: Single Condition Filtering (5 points)

1. Filter employees who left the company (Attrition == 'Yes')
2. Filter employees with MonthlyIncome greater than 10000
3. Filter employees in the 'Research & Development' department

In [107]:
###1.Filter employees who left the company (Attrition == 'Yes')
df[df['Attrition']== 'Yes']

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
14,28,Yes,Travel_Rarely,103,Research & Development,24,3,Life Sciences,1,19,...,2,80,0,6,4,3,4,2,0,3
21,36,Yes,Travel_Rarely,1218,Sales,9,4,Life Sciences,1,27,...,2,80,0,10,4,3,5,3,0,3
24,34,Yes,Travel_Rarely,699,Research & Development,6,1,Medical,1,31,...,3,80,0,8,2,3,4,2,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1438,23,Yes,Travel_Frequently,638,Sales,9,3,Marketing,1,2023,...,1,80,1,1,3,2,1,0,1,0
1442,29,Yes,Travel_Rarely,1092,Research & Development,1,4,Medical,1,2027,...,2,80,3,4,3,4,2,2,2,2
1444,56,Yes,Travel_Rarely,310,Research & Development,7,2,Technical Degree,1,2032,...,4,80,1,14,4,1,10,9,9,8
1452,50,Yes,Travel_Frequently,878,Sales,1,4,Life Sciences,1,2044,...,4,80,2,12,3,3,6,3,0,1
1461,50,Yes,Travel_Rarely,410,Sales,28,3,Marketing,1,2055,...,2,80,1,20,3,3,3,2,2,0

In [108]:
###2.Filter employees with MonthlyIncome greater than 10000
df[df['MonthlyIncome'] > 10000]

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
18,53,No,Travel_Rarely,1219,Sales,2,4,Life Sciences,1,23,...,3,80,0,31,3,3,25,8,3,7
22,34,No,Travel_Rarely,419,Research & Development,7,4,Life Sciences,1,28,...,3,80,0,13,4,3,12,6,2,11
25,53,No,Travel_Rarely,1282,Research & Development,5,3,Other,1,32,...,4,80,1,26,3,2,14,13,4,8
28,44,No,Travel_Rarely,477,Research & Development,7,4,Medical,1,36,...,4,80,1,24,4,3,22,6,5,17
29,46,No,Travel_Rarely,705,Sales,2,4,Marketing,1,38,...,4,80,0,22,2,2,2,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1437,39,No,Non-Travel,105,Research & Development,9,3,Life Sciences,1,2022,...,3,80,0,21,3,2,6,0,1,3
1443,42,No,Travel_Rarely,300,Research & Development,2,3,Life Sciences,1,2031,...,1,80,0,24,2,2,22,6,4,14
1445,41,No,Travel_Rarely,582,Research & Development,28,4,Life Sciences,1,2034,...,3,80,1,21,3,3,20,7,0,10
1461,50,Yes,Travel_Rarely,410,Sales,28,3,Marketing,1,2055,...,2,80,1,20,3,3,3,2,2,0
1462,39,No,Travel_Rarely,722,Sales,24,1,Marketing,1,2056,...,1,80,1,21,2,2,20,9,9,6

In [109]:
###3.Filter employees in the 'Research & Development' department
df[df['Department'] == 'Research & Development']

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
5,32,No,Travel_Frequently,1005,Research & Development,2,2,Life Sciences,1,8,...,3,80,0,8,2,2,7,7,3,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1463,31,No,Non-Travel,325,Research & Development,5,3,Medical,1,2057,...,2,80,0,10,2,3,9,4,1,7
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

### Task 3.2: Multiple Condition Filtering (10 points)

Remember: Use & for AND, | for OR, ~ for NOT. Always use parentheses!

1. Employees who left AND had low job satisfaction (JobSatisfaction == 1)
2. Employees in Sales OR with MonthlyIncome > 15000
3. Employees NOT married AND with more than 10 years at company
4. Employees aged 30-40 (inclusive) who work overtime

In [110]:
###1.Employees who left AND had low job satisfaction (JobSatisfaction == 1)
df[(df['Attrition']== 'Yes') & (df['JobSatisfaction'] ==1)]

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
21,36,Yes,Travel_Rarely,1218,Sales,9,4,Life Sciences,1,27,...,2,80,0,10,4,3,5,3,0,3
24,34,Yes,Travel_Rarely,699,Research & Development,6,1,Medical,1,31,...,3,80,0,8,2,3,4,2,1,3
26,32,Yes,Travel_Frequently,1125,Research & Development,16,1,Life Sciences,1,33,...,2,80,0,10,5,3,10,2,6,7
100,37,Yes,Travel_Rarely,807,Human Resources,6,4,Human Resources,1,133,...,4,80,0,7,3,3,3,2,0,2
140,32,Yes,Travel_Rarely,1033,Research & Development,9,3,Medical,1,190,...,1,80,0,10,2,4,5,4,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1353,34,Yes,Non-Travel,967,Research & Development,16,4,Technical Degree,1,1905,...,2,80,1,5,2,3,5,2,3,0
1365,29,Yes,Travel_Frequently,746,Sales,24,3,Technical Degree,1,1928,...,4,80,0,1,3,3,1,0,0,0
1396,53,Yes,Travel_Rarely,1168,Sales,24,4,Life Sciences,1,1968,...,2,80,0,15,2,2,2,2,2,2
1438,23,Yes,Travel_Frequently,638,Sales,9,3,Marketing,1,2023,...,1,80,1,1,3,2,1,0,1,0
1461,50,Yes,Travel_Rarely,410,Sales,28,3,Marketing,1,2055,...,2,80,1,20,3,3,3,2,2,0

In [111]:
###2.Employees in Sales OR with MonthlyIncome > 15000
df[(df['Department'] == 'Sales') | (df['MonthlyIncome'] > 15000)]

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
18,53,No,Travel_Rarely,1219,Sales,2,4,Life Sciences,1,23,...,3,80,0,31,3,3,25,8,3,7
21,36,Yes,Travel_Rarely,1218,Sales,9,4,Life Sciences,1,27,...,2,80,0,10,4,3,5,3,0,3
25,53,No,Travel_Rarely,1282,Research & Development,5,3,Other,1,32,...,4,80,1,26,3,2,14,13,4,8
27,42,No,Travel_Rarely,691,Sales,8,4,Marketing,1,35,...,4,80,1,10,2,3,9,7,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,45,No,Travel_Rarely,374,Sales,20,3,Life Sciences,1,2046,...,3,80,0,8,3,3,5,3,0,1
1461,50,Yes,Travel_Rarely,410,Sales,28,3,Marketing,1,2055,...,2,80,1,20,3,3,3,2,2,0
1462,39,No,Travel_Rarely,722,Sales,24,1,Marketing,1,2056,...,1,80,1,21,2,2,20,9,9,6
1464,26,No,Travel_Rarely,1167,Sales,5,3,Other,1,2060,...,4,80,0,5,2,3,4,2,0,0
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8

In [112]:
###3.Employees NOT married AND with more than 10 years at company
df[(df['MaritalStatus'] != 'Married') & (df['YearsAtCompany'] > 10)]

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
22,34,No,Travel_Rarely,419,Research & Development,7,4,Life Sciences,1,28,...,3,80,0,13,4,3,12,6,2,11
25,53,No,Travel_Rarely,1282,Research & Development,5,3,Other,1,32,...,4,80,1,26,3,2,14,13,4,8
44,30,No,Travel_Frequently,721,Research & Development,1,2,Medical,1,57,...,4,80,0,12,2,3,12,8,3,7
55,33,No,Travel_Frequently,515,Research & Development,1,2,Life Sciences,1,73,...,3,80,0,15,1,3,15,14,8,12
62,50,No,Travel_Rarely,989,Research & Development,7,2,Medical,1,80,...,4,80,1,29,2,2,27,3,13,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1403,39,No,Travel_Rarely,119,Sales,15,4,Marketing,1,1975,...,1,80,0,21,3,3,20,8,11,10
1404,42,No,Non-Travel,335,Research & Development,23,2,Life Sciences,1,1976,...,4,80,0,20,2,3,20,9,3,7
1414,47,No,Travel_Rarely,1180,Research & Development,25,3,Medical,1,1993,...,2,80,0,25,3,3,17,14,12,11
1441,56,No,Non-Travel,667,Research & Development,1,4,Life Sciences,1,2026,...,1,80,1,13,2,2,13,12,1,9
1447,36,No,Non-Travel,301,Sales,15,4,Marketing,1,2036,...,1,80,1,15,4,2,15,12,11,11

In [113]:
###4.Employees aged 30-40 (inclusive) who work overtime
df[(df['Age'].between(30,40)) & (df['OverTime'] == 'Yes')]

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
16,32,No,Travel_Rarely,334,Research & Development,5,2,Life Sciences,1,21,...,4,80,2,7,5,2,6,2,0,5
19,38,No,Travel_Rarely,371,Research & Development,2,3,Life Sciences,1,24,...,3,80,0,6,3,3,3,2,1,2
26,32,Yes,Travel_Frequently,1125,Research & Development,16,1,Life Sciences,1,33,...,2,80,0,10,5,3,10,2,6,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1422,35,No,Travel_Rarely,1490,Research & Development,11,4,Medical,1,2003,...,3,80,1,5,3,3,2,2,2,2
1425,33,No,Travel_Rarely,501,Research & Development,15,2,Medical,1,2009,...,1,80,1,10,6,3,9,7,8,1
1432,37,No,Travel_Rarely,161,Research & Development,10,3,Life Sciences,1,2017,...,1,80,1,16,2,3,16,11,6,8
1450,35,No,Travel_Rarely,1146,Human Resources,26,4,Life Sciences,1,2040,...,3,80,0,9,2,3,9,0,1,7
1456,35,No,Travel_Frequently,1199,Research & Development,18,4,Life Sciences,1,2049,...,4,80,2,10,2,4,10,2,0,2

### Task 3.3: Using isin() (5 points)

1. Filter employees in departments: 'Sales', 'Human Resources'
2. Filter employees with JobLevel in [1, 2, 3]
3. Filter employees NOT in job roles: 'Sales Executive', 'Research Scientist'

In [114]:
###1.Filter employees in departments: 'Sales', 'Human Resources'
departments_list = ['Sales', 'Human Resources']
filtered_dept = df[df['Department'].isin(departments_list)]

In [115]:
###2.Filter employees with JobLevel in [1, 2, 3]
levels_list = [1, 2, 3]
filtered_levels = df[df['JobLevel'].isin(levels_list)]

In [116]:
###3.Filter employees NOT in job roles: 'Sales Executive', 'Research Scientist'
excluded_roles = ['Sales Executive', 'Research Scientist']
filtered_excluded_roles = df[~df['JobRole'].isin(excluded_roles)]

---
## Part 4: Value Counts and Categorical Analysis (15 points)
---

### Task 4.1: Basic value_counts() (5 points)

1. Count employees by Department
2. Count employees by Attrition status
3. Count employees by JobRole, sorted by count

In [117]:
###1.Count employees by Department
df['Department'].value_counts()

Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

In [118]:
###2.Count employees by Attrition status
df['Attrition'].value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [119]:
###3.Count employees by JobRole, sorted by count
df['JobRole'].value_counts()

JobRole
Sales Executive              326
Research Scientist           292
Laboratory Technician        259
Manufacturing Director       145
Healthcare Representative    131
Manager                      102
Sales Representative          83
Research Director             80
Human Resources               52
Name: count, dtype: int64

### Task 4.2: value_counts() with Parameters (5 points)

1. Show proportion of employees in each Department (normalize=True)
2. Show value counts for JobSatisfaction including NaN (dropna=False)
3. Show top 5 most common EducationField values

In [120]:
###1.Show proportion of employees in each Department (normalize=True)
df['Department'].value_counts(normalize=True) * 100

Department
Research & Development    65.374150
Sales                     30.340136
Human Resources            4.285714
Name: proportion, dtype: float64

In [121]:
###2.Show value counts for JobSatisfaction including NaN (dropna=False)
df['JobSatisfaction'].value_counts(dropna=False)

JobSatisfaction
4    459
3    442
1    289
2    280
Name: count, dtype: int64

In [122]:
###3.Show top 5 most common EducationField values
df['EducationField'].value_counts().head(5)

EducationField
Life Sciences       606
Medical             464
Marketing           159
Technical Degree    132
Other                82
Name: count, dtype: int64

### Task 4.3: Unique Values (5 points)

1. Find all unique values in 'MaritalStatus'
2. Count number of unique JobRoles
3. Find number of unique Department-JobRole combinations

In [123]:
###1.Find all unique values in 'MaritalStatus'
df['MaritalStatus'].unique()

array(['Single', 'Married', 'Divorced'], dtype=object)

In [124]:
###2.Count number of unique JobRoles
df['JobRole'].nunique()

9

In [125]:
###3.Find number of unique Department-JobRole combinations
len(df[['Department', 'JobRole']].drop_duplicates())

11

---
## Part 5: Apply and Map Functions (20 points)
---

### Task 5.1: Using map() (5 points)

1. Create 'Attrition_Binary': map 'Yes' to 1, 'No' to 0
2. Create 'Gender_Full': map 'Male' to 'Male Employee', 'Female' to 'Female Employee'
3. Create 'Satisfaction_Label': map 1='Low', 2='Medium', 3='High', 4='Very High'

In [126]:
###1 Create 'Attrition_Binary': map 'Yes' to 1, 'No' to 0
attrition_dic = {'Yes' : 1, 'No' : 0}
df['Attrition_Binary'] = df['Attrition'].map(attrition_dic)
df['Attrition_Binary']

0       1
1       0
2       1
3       0
4       0
       ..
1465    0
1466    0
1467    0
1468    0
1469    0
Name: Attrition_Binary, Length: 1470, dtype: int64

In [127]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [128]:
###2 Create 'Gender_Full': map 'Male' to 'Male Employee', 'Female' to 'Female Employee'
df['Gender'] = df['Gender'].astype(str).str.strip()
gender_dic = {'Male' : 'Male Employee', 'Female' : 'Female Employee'}
df['Gender_Full'] = df['Gender'].map(gender_dic)
df['Gender_Full']

0       Female Employee
1         Male Employee
2         Male Employee
3       Female Employee
4         Male Employee
             ...
1465      Male Employee
1466      Male Employee
1467      Male Employee
1468      Male Employee
1469      Male Employee
Name: Gender_Full, Length: 1470, dtype: object

In [129]:
###3 Create 'Satisfaction_Label': map 1='Low', 2='Medium', 3='High', 4='Very High'
satisfaction_dic = {1 : 'Low', 2 : 'Medium', 3 : 'High', 4 : 'Very High'}
df['Satisfaction_Label'] = df['JobSatisfaction'].map(satisfaction_dic)
df['Satisfaction_Label']

0       Very High
1          Medium
2            High
3            High
4          Medium
          ...
1465    Very High
1466          Low
1467       Medium
1468       Medium
1469         High
Name: Satisfaction_Label, Length: 1470, dtype: object

### Task 5.2: Using apply() with Lambda (10 points)

1. Create 'AgeGroup':
   - Under 30: 'Young'
   - 30-45: 'Mid-Career'
   - Over 45: 'Senior'

2. Create 'IncomeLevel':
   - Below 3000: 'Low'
   - 3000-7000: 'Medium'
   - Above 7000: 'High'

3. Create 'TenureRatio': YearsAtCompany / TotalWorkingYears (handle division by zero)

In [130]:
###1 Create 'AgeGroup': Under 30: 'Young' 30-45: 'Mid-Career' Over 45: 'Senior'
df['AgeGroup'] = df['Age'].apply(lambda x :'Young' if x < 30 else ('Mid-Career'if x <= 45 else 'Senior' ))
df['AgeGroup']

0       Mid-Career
1           Senior
2       Mid-Career
3       Mid-Career
4            Young
           ...
1465    Mid-Career
1466    Mid-Career
1467         Young
1468        Senior
1469    Mid-Career
Name: AgeGroup, Length: 1470, dtype: object

In [131]:
###2 Create 'IncomeLevel': Below 3000: 'Low' 3000-7000: 'Medium' Above 7000: 'High'
df['IncomeLevel'] = df['MonthlyIncome'].apply(lambda x : 'low' if x < 3000 else('medium' if x<= 7000 else 'high'))
df['IncomeLevel']

0       medium
1       medium
2          low
3          low
4       medium
         ...
1465       low
1466      high
1467    medium
1468    medium
1469    medium
Name: IncomeLevel, Length: 1470, dtype: object

In [132]:
###3 Create 'TenureRatio': YearsAtCompany / TotalWorkingYears (handle division by zero)
df['TenureRatio'] = df.apply(lambda row : row['YearsAtCompany'] / row['TotalWorkingYears'] if row['TotalWorkingYears'] >0 else 0, axis = 1 )
df['TenureRatio']

0       0.750000
1       1.000000
2       0.000000
3       1.000000
4       0.333333
          ...
1465    0.294118
1466    0.777778
1467    1.000000
1468    0.529412
1469    0.666667
Name: TenureRatio, Length: 1470, dtype: float64

### Task 5.3: Custom Functions with apply() (5 points)

1. Write a function that returns 'High Risk' if JobSatisfaction <= 2 AND WorkLifeBalance <= 2, else 'Normal'
   Apply to create 'RiskCategory' column

2. Calculate 'AnnualIncome' (MonthlyIncome * 12) using apply

In [133]:
###1 Write a function that returns 'High Risk' if JobSatisfaction <= 2 AND WorkLifeBalance <= 2, else 'Normal' Apply to create 'RiskCategory' column
def calculate_risk(row):
    if row['JobSatisfaction'] <= 2 and row['WorkLifeBalance'] <= 2:
        return 'High Risk'
    else:
        return 'Normal'

df['RiskCategory'] = df.apply(calculate_risk, axis=1)
df['RiskCategory']

0          Normal
1          Normal
2          Normal
3          Normal
4          Normal
          ...
1465       Normal
1466       Normal
1467       Normal
1468    High Risk
1469       Normal
Name: RiskCategory, Length: 1470, dtype: object

In [134]:
###2 Calculate 'AnnualIncome' (MonthlyIncome * 12) using apply
df['AnnualIncome'] = df['MonthlyIncome'].apply(lambda x: x * 12)
df['AnnualIncome']

0        71916
1        61560
2        25080
3        34908
4        41616
         ...
1465     30852
1466    119892
1467     73704
1468     64680
1469     52848
Name: AnnualIncome, Length: 1470, dtype: int64

---
## Part 6: Sorting and Ranking (10 points)
---

### Task 6.1: Sorting (5 points)

1. Sort by MonthlyIncome descending, show top 10
2. Sort by Department (asc) then Age (desc)
3. Show 5 longest-tenured employees

In [135]:
###1Sort by MonthlyIncome descending, show top 10
df.sort_values(by = 'MonthlyIncome', ascending = False).head(10)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,YearsSinceLastPromotion,YearsWithCurrManager,Attrition_Binary,Gender_Full,Satisfaction_Label,AgeGroup,IncomeLevel,TenureRatio,RiskCategory,AnnualIncome
190,52,No,Travel_Rarely,699,Research & Development,1,4,Life Sciences,1,259,...,11,9,0,Male Employee,High,Senior,high,0.970588,Normal,239988
746,41,No,Non-Travel,247,Research & Development,7,1,Life Sciences,1,1035,...,5,10,0,Female Employee,High,Mid-Career,high,1.000000,Normal,239676
851,56,No,Travel_Rarely,718,Research & Development,4,4,Technical Degree,1,1191,...,4,2,0,Female Employee,Low,Senior,high,0.178571,Normal,239316
165,50,No,Travel_Rarely,1452,Research & Development,11,3,Life Sciences,1,226,...,4,4,0,Female Employee,Medium,Senior,high,0.238095,Normal,239112
568,55,Yes,Travel_Rarely,725,Research & Development,2,3,Medical,1,787,...,1,4,1,Male Employee,Low,Senior,high,0.208333,Normal,238308
918,51,No,Travel_Frequently,237,Sales,9,3,Life Sciences,1,1282,...,11,10,0,Male Employee,Medium,Senior,high,0.935484,High Risk,238164
749,52,Yes,Travel_Rarely,266,Sales,2,1,Marketing,1,1038,...,6,9,1,Female Employee,Very High,Senior,high,0.969697,Normal,238140
1242,40,No,Travel_Rarely,611,Sales,7,4,Medical,1,1740,...,12,8,0,Male Employee,Medium,Mid-Career,high,1.000000,High Risk,237996
898,43,No,Travel_Rarely,920,Research & Development,3,3,Life Sciences,1,1255,...,0,7,0,Male Employee,Very High,Mid-Career,high,0.320000,Normal,236880
956,56,No,Travel_Rarely,206,Human Resources,8,4,Life Sciences,1,1338,...,7,7,0,Male Employee,Medium,Senior,high,0.194444,Normal,236604

In [136]:
###2 Sort by Department (asc) then Age (desc)
df.sort_values(by = ['Department', 'Age'], ascending=[True,False])

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,YearsSinceLastPromotion,YearsWithCurrManager,Attrition_Binary,Gender_Full,Satisfaction_Label,AgeGroup,IncomeLevel,TenureRatio,RiskCategory,AnnualIncome
105,59,No,Non-Travel,1420,Human Resources,2,4,Human Resources,1,140,...,2,2,0,Female Employee,Very High,Senior,high,0.100000,Normal,226128
232,59,No,Travel_Rarely,818,Human Resources,6,2,Medical,1,321,...,2,2,0,Male Employee,High,Senior,low,0.285714,Normal,27204
956,56,No,Travel_Rarely,206,Human Resources,8,4,Life Sciences,1,1338,...,7,7,0,Male Employee,Medium,Senior,high,0.194444,Normal,236604
1401,55,No,Travel_Rarely,189,Human Resources,26,4,Human Resources,1,1973,...,1,4,0,Male Employee,Medium,Senior,high,0.285714,Normal,235632
112,54,No,Non-Travel,142,Human Resources,26,3,Human Resources,1,148,...,4,4,0,Female Employee,Very High,Senior,high,0.217391,Normal,207936
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,19,Yes,Travel_Frequently,602,Sales,1,1,Technical Degree,1,235,...,0,0,1,Female Employee,Low,Young,low,0.000000,Normal,27900
688,19,Yes,Travel_Rarely,419,Sales,21,3,Other,1,959,...,0,0,1,Male Employee,Medium,Young,low,1.000000,Normal,25452
301,18,No,Travel_Rarely,812,Sales,10,3,Medical,1,411,...,0,0,0,Female Employee,High,Young,low,0.000000,Normal,14400
457,18,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,1,614,...,0,0,1,Male Employee,Medium,Young,low,0.000000,Normal,22536
1153,18,Yes,Travel_Frequently,544,Sales,3,2,Medical,1,1624,...,0,0,1,Female Employee,Very High,Young,low,0.000000,Normal,18828

In [137]:
###3 Show 5 longest-tenured employees
df.sort_values(by = 'YearsAtCompany', ascending=False).head(5)

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,YearsSinceLastPromotion,YearsWithCurrManager,Attrition_Binary,Gender_Full,Satisfaction_Label,AgeGroup,IncomeLevel,TenureRatio,RiskCategory,AnnualIncome
126,58,Yes,Travel_Rarely,147,Research & Development,23,4,Medical,1,165,...,15,6,1,Female Employee,Very High,Senior,high,1.000000,Normal,123744
98,58,No,Travel_Rarely,682,Sales,10,4,Medical,1,131,...,1,8,0,Male Employee,High,Senior,high,0.973684,Normal,166464
1116,55,No,Travel_Rarely,685,Sales,26,5,Marketing,1,1578,...,2,13,0,Male Employee,Very High,Senior,high,1.000000,Normal,235032
270,55,No,Travel_Rarely,452,Research & Development,1,3,Medical,1,374,...,4,13,0,Male Employee,Low,Senior,high,0.972973,Normal,228540
561,52,No,Travel_Rarely,621,Sales,3,4,Marketing,1,776,...,1,16,0,Male Employee,Low,Senior,high,1.000000,Normal,202272

### Task 6.2: Ranking (5 points)

1. Create 'IncomeRank' ranking by MonthlyIncome (highest = 1)
2. Create 'AgeRank' using method='dense'
3. Find employee(s) with IncomeRank = 1

In [138]:
###1 Create 'IncomeRank' ranking by MonthlyIncome (highest = 1)
df['IncomeRank'] = df['MonthlyIncome'].rank(ascending=False)
df['IncomeRank']

0        557.5
1        701.0
2       1401.0
3       1104.5
4       1004.0
         ...
1465    1220.0
1466     283.0
1467     544.0
1468     647.0
1469     840.0
Name: IncomeRank, Length: 1470, dtype: float64

In [139]:
###2 Create 'AgeRank' using method='dense'
df['AgeRank'] = df['Age'].rank(method = 'dense')

In [140]:
###3 Find employee(s) with IncomeRank = 1
df[df['IncomeRank'] == 1]

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,Attrition_Binary,Gender_Full,Satisfaction_Label,AgeGroup,IncomeLevel,TenureRatio,RiskCategory,AnnualIncome,IncomeRank,AgeRank
190,52,No,Travel_Rarely,699,Research & Development,1,4,Life Sciences,1,259,...,0,Male Employee,High,Senior,high,0.970588,Normal,239988,1.0,35.0

---
## Part 7: Business Analysis Questions (5 points)
---

Answer with code and brief explanations:

1. What is the overall attrition rate?
2. Which department has the highest attrition rate?
3. Average monthly income: left vs stayed?
4. What percentage of leavers had low job satisfaction (1 or 2)?
5. Is there a relationship between overtime and attrition?

In [141]:
###1 What is the overall attrition rate?
(df['Attrition']== 'Yes').mean() * 100
######## the percentage of people who had left the job is almost 16 %

np.float64(16.122448979591837)

In [142]:
###2 Which department has the highest attrition rate?
filterd_attrition = df.groupby('Department')['Attrition'].apply(lambda x : (x == 'Yes').mean() * 100)
filterd_attrition.idxmax()
#### Hence, Sales Department has the heighest attrition rate

'Sales'

In [143]:
###3 Average monthly income: left vs stayed?
df.groupby('Attrition')['MonthlyIncome'].mean()
###### avg for stayed is larger than who left.

Attrition
No     6832.739659
Yes    4787.092827
Name: MonthlyIncome, dtype: float64

In [144]:
###4 What percentage of leavers had low job satisfaction (1 or 2)?
leavers = df[df['Attrition'] == 'Yes']
(leavers['JobSatisfaction'] <= 2 ).mean() * 100
######## percentage of leavers had low job satisfaction (1 or 2) is 47 %

np.float64(47.257383966244724)

In [145]:
###5 Is there a relationship between overtime and attrition?
df.groupby('OverTime')['Attrition'].apply(lambda x : (x == 'Yes').mean() * 100)
###### absolutely there is a relationship between overtime and attrition.

OverTime
No     10.436433
Yes    30.528846
Name: Attrition, dtype: float64

### Your Findings:

1. Overall attrition rate:
2. Department with highest attrition:
3. Income comparison:
4. Low satisfaction percentage:
5. Overtime relationship:

---
## Bonus Challenge (10 extra points)
---

Create a summary DataFrame showing for each Department:

- Total employees
- Number who left
- Attrition rate
- Average MonthlyIncome
- Average YearsAtCompany

In [146]:
# BONUS CODE HERE
summary_df = df.groupby('Department').agg(
  Total_employees = ('Attrition', 'count'),
  Number_who_left = ('Attrition', lambda x :( x == 'Yes').sum()),
  Attrition_rate = ('Attrition', lambda x : (x == 'Yes').mean()*100),
  Average_MonthlyIncome = ('MonthlyIncome', 'mean'),
  Average_YearsAtCompany = ('YearsAtCompany', 'mean')
)
summary_df

,Total_employees,Number_who_left,Attrition_rate,Average_MonthlyIncome,Average_YearsAtCompany
Department,,,,,
Human Resources,63,12,19.047619,6654.507937,7.238095
Research & Development,961,133,13.839750,6281.252862,6.864724
Sales,446,92,20.627803,6959.172646,7.284753

In [147]:
summary_df['Attrition_rate'] = summary_df['Attrition_rate'].round(2)
summary_df['Average_MonthlyIncome'] = summary_df['Average_MonthlyIncome'].round(2)
summary_df['Average_YearsAtCompany'] = summary_df['Average_YearsAtCompany'].round(2)
summary_df

,Total_employees,Number_who_left,Attrition_rate,Average_MonthlyIncome,Average_YearsAtCompany
Department,,,,,
Human Resources,63,12,19.05,6654.51,7.24
Research & Development,961,133,13.84,6281.25,6.86
Sales,446,92,20.63,6959.17,7.28

---
## Submission Checklist

- [ ] All code cells run without errors
- [ ] All tasks completed
- [ ] Analysis questions answered
- [ ] Code is commented

**Total Points: 100 (+ 10 bonus)**